name: epub_to_audio
description: A Flutter application to convert EPUB books to audio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.5
  http: ^0.13.6
  path_provider: ^2.1.1
  path: ^1.8.3
  epub_parser: ^3.0.1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
